name: Sync with S3

on:
  workflow_dispatch: #Can manually trigger
  pull_request_target:
    types: [ closed ] #Runs on PR merge
    branches: [ main ]
    
jobs: 
  sync:
    #PR merged with main                            #Manually triggered workflow
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: hellocoop/tools/.github/workflows/content-sync.yml@main
    # GitHub-Slack app sends a workflow status message with live updates to #content-updates channel
    with:
      STACK: PlaygroundStack #make sure this is the right stack value #TBD: use env